src/configuration.ts

We tried to use `valuesAreDifferent` in #56 for checking if individual values match, but because inside that function we make an explicit check for `undefined` this breaks the functionality and always skips deciding for each setting.
Additionally, we hadn't updated our `allSettingsMatch` equality check to use stringify. I made that change and also started not prompting users at all if all values already match.

Fix decide for each equality check

---

src/configuration.ts

Add automatic white space trimming and new line insertion to our configs. Both are `false` by default, but then we either catch them with linters or even in PR reviews, so might as well have it automatically configured.

Add line trimming and final new line insertion

---

README.md

It'd be nice if we can also link to the extension page from the readme without manually searching it 🙂 
(I'm used to browse extensions on GH and click links to their marketplace)
I know the readme will also appear in the extension page so the link to it will redirect back to itself (or just do nothing?). But I guess that'll be fine.

Add a link to marketplace page

---

package.json
src/configuration.ts
src/extension.ts

Continuation of #85.
Remove the `rubocop-lsp` from the pack, change the default formatter to be the `ruby-lsp` and prompt users to swap the `rubocop-lsp` gem for the `ruby-lsp` in case the gem is still present.
I attempted to be smart about it and add a button for removing `rubocop-lsp` with `bundle remove` and then adding the `ruby-lsp`, but depending on how the Gemfile groups are organized the results can vary. So, I ended up picking the simple path and just made it display a modal prompting the user to take the action manually.
1. Start the plugin on this branch
2. On the opened window, navigate to a project that uses the `rubocop-lsp`
3. Verify you get prompted with a modal

Remove the rubocop-lsp plugin

---

src/configuration.ts
src/configurationStore.ts
src/setting.ts
src/test/fakeStore.ts
src/test/suite/configuration.test.ts
src/test/suite/setting.test.ts

Closes #68
We always apply our setting recommendations on the global (user) settings. However, if a workspace setting exists (under `.vscode/settings.json`) it will always take precedence over what we configure and this can be confusing for users that expect out recommendation to be applied.
While trying to work on this, I realized the code was getting way too complicated to navigate and make changes, so I had to make a refactor first to facilitate this change.
1. Moved the test's `FakeStore` to a separate file so that other tests can use it too
2. Moved some interfaces and constants into `configurationStore`, so that multiple classes can access it
3. Extracted a `Setting` class, which is now responsible for everything related to a single setting, like checking whether the stored value is …

Warn users about workspace settings shadowing recommended defaults

---

src/configuration.ts

We have received some reports that Ruby files are sometimes incorrectly configured to use tabs instead of spaces. We can fix that easily by pushing the recommended settings for Ruby.

Configure Ruby files to use 2 spaces for indentation

---

src/configuration.ts
src/setting.ts

Closes #116 
During set up, having the button say `Apply` makes more sense than `Override` in cases when there is no default to override.
1. Changed the button `Override All` for the question "Would you like to apply all of the suggested configuration defaults?" to `Apply All`
2. Modified the `promptOverride()` function to check if there is an existing config for the setting and if not to change the message & button options displayed
**Setting exists**
**Setting does not exist**
1. Open up a repository with the debugger on VSCode (`Function + F5`)
2. If prompted by the VSCode extension to apply the suggested configuration defaults, `Apply All`
3. Open up `settings.json`(not the default or workspace settings)
4. Delete some of the settings (e.g.,`byesig.opacity`)
5. Change some of the …

Change button wording for clarity

---

src/configuration.ts

Reverts Shopify/vscode-shopify-ruby#123
This was fixed in https://github.com/Shopify/ruby-lsp/pull/149
🎩 and it seemed to work nicely.

Enable formatOnSave

---

CHANGELOG.md
package.json

Bump to version 0.0.7. The version includes our new logo and the configuration for the editor ruler.

Bump to version v0.0.7

---

src/configuration.ts

The default value of the `semanticHighlighting.enabled` configuration is `configuredByTheme`. This means that, if the theme doesn't turn on semantic highlighting, folks are actually not getting any of it.
I propose we turn this on by default, given that the Ruby LSP can provide semantic highlighting. Thoughts?

Auto-enable semantic highlighting for Ruby

---

README.md
package.json
src/configuration.ts
src/extension.ts

Start the process of deprecating and removing Rebornix Ruby from the extension pack
This PR introduces some changes from the list of todo in: https://github.com/Shopify/ruby-dev-exp-issues/issues/533#issuecomment-1129185226 
- Remove Rebornix.Ruby from the extensions pack
-  Set all of the Rebornix.Ruby related configuration values to be undefined, so that they are removed from people's configuration
- Simple warning that Rebornix.Ruby is deprecated
* Make sure there are some `rebornix-ruby` configurations in your settings.json, example: 
```json
"ruby.format": "prettier",
"ruby.lint": {
"enabled": true,
"ignored": [
"**/vendor/**",
"**/node_modules/**",
"**/bower_components/**"
],
"rubocop": {
"enabled": true,
"ignored": [
"**/vendor/**",
"**/node_modules/**",
"**/bower_components/**"
] …
```

Deprecate and remove rebornix-ruby 

---

src/configuration.ts

The work on https://github.com/Shopify/vscode-ruby-lsp/pull/193 and https://github.com/Shopify/ruby-lsp/pull/253 only works if `formatOnType` is enabled.
This PR enables it for Ruby.

Enable format on type for Ruby

---

.yarnrc

This is a very minor improvement. When we run yarn commands, it complains that it doesn't recognize the engine "vscode". We can configure yarn to ignore unknown engines, which we already do in `vscode-ruby-lsp`.

Ignore unknown yarn engines

---

package.json
yarn.lock

The `vsce` is [deprecated](https://www.npmjs.com/package/vsce) and contains a security vulnerability. We need to switch to `@vscode/vsce`.
- `yarn remove vsce`
- `yarn add @vscode/vsce`

Switch to use @vscode/vsce

---

src/configuration.ts

Scope all of our setting recommendations to only apply to the Ruby language. Also took the chance and added `trimFinalNewlines`, which ensures that there isn't more than one line at the end of the file.

Scope all settings to Ruby

---

themes/dark_spinel.json

We were missing this scope and then properties defined with `#property` were highlighted inconsistently.

Add missing `variable.other.object.property` scope

---

README.md

Related to https://github.com/Shopify/vscode-shopify-ruby/issues/579
Make it clearer that the extension pack includes Sorbet that's conditionally activated. Also that the debugger extension is on its way out. This should help reduce confusion for some folks unsure if this extension is right for them.

Update README note

---

README.md

Let's make it clearer in the documentation of this extension pack that no Ruby features are implemented by it, but instead by the extensions included in the pack.

Add README note about the features included

---

README.md
package.json

Now that the debugger client built into the Ruby LSP supports configuring sockets and ports for attaching, we are pretty much at feature parity and can remove the RDBG extension from the pack.

Remove RDBG extension from the pack

---

.github/workflows/ci.yml
.github/workflows/publish.yml
dev.yml
package.json
yarn.lock

Closes https://github.com/Shopify/vscode-shopify-ruby/issues/646

Publish on OpenVSX

---

README.md

Since the other repo has been archived, point directly to the relevant repo.

Update Ruby-LSP repo url
